# Generated by Django 2.2.7 on 2020-01-12 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDescription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=30)),
                ('payments', models.CharField(max_length=30)),
                ('paymentsFrequency', models.CharField(max_length=10)),
                ('startDate', models.DateField(max_length=12)),
                ('noofperiod', models.IntegerField(null=True)),
                ('createBy', models.IntegerField()),
                ('isActive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('payStatus', models.IntegerField()),
                ('payoutOrder', models.IntegerField()),
                ('groupdescpID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvitationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.IntegerField()),
                ('emailID', models.CharField(max_length=30)),
                ('isInvite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('paidFrequency', models.IntegerField()),
                ('paidDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserbankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('bankaddress', models.IntegerField()),
                ('bankname', models.CharField(max_length=30)),
                ('accountnumer', models.IntegerField()),
                ('ifscCode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userPoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbirth', models.DateField(blank=True, max_length=8, null=True)),
                ('mobilenumber', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=30)),
                ('addressLine2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('postelCode', models.IntegerField()),
                ('ssnnNmber', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
