# Generated by Django 2.2.7 on 2019-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('addressline1', models.CharField(max_length=30)),
                ('addressline2', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postelcode', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mobilenumber', models.IntegerField(max_length=12)),
                ('ssnnumber', models.IntegerField(max_length=12)),
                ('phoneenumber', models.IntegerField(max_length=12)),
            ],
        ),
    ]
