# Generated by Django 2.2.7 on 2020-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postelCode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='ssnnNmber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobilenumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
