# Generated by Django 2.2.7 on 2019-11-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('moneymanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=30)),
                ('addressLine2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('postelCode', models.IntegerField(max_length=12)),
                ('ssnnNmber', models.IntegerField(max_length=9)),
                ('country', models.CharField(max_length=30)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=30)),
                ('payments', models.CharField(max_length=30)),
                ('paymentsFrequency', models.IntegerField(max_length=5)),
                ('startDate', models.DateField(max_length=12)),
                ('endDate', models.DateField(max_length=9)),
                ('createBy', models.IntegerField(max_length=30)),
                ('isActive', models.IntegerField(max_length=1)),
                ('groupID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(max_length=30)),
                ('payStatus', models.IntegerField(max_length=1)),
                ('payoutOrder', models.IntegerField(max_length=30)),
                ('groupdescID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanagement.GroupDescription')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.IntegerField(max_length=30)),
                ('userID', models.IntegerField(max_length=30)),
                ('isInvite', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(max_length=30)),
                ('paidFrequency', models.IntegerField(max_length=30)),
                ('paidDate', models.DateField(max_length=30)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanagement.GroupDescription')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('mobilenumber', models.IntegerField(max_length=10)),
                ('phoneenumber', models.IntegerField(max_length=10)),
                ('profilepic', models.ImageField(upload_to='')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(max_length=30)),
                ('userPoint', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
