# Generated by Django 2.2.7 on 2020-01-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0002_auto_20200112_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdescription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitationdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlypaymentdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
