# Generated by Django 2.2.7 on 2019-11-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0002_auto_20191119_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationdetails',
            old_name='userID',
            new_name='emailID',
        ),
    ]
