# Generated by Django 2.2.7 on 2020-01-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0003_auto_20200112_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ssnnNmber',
            field=models.TextField(null=True),
        ),
    ]
