# Generated by Django 2.2.7 on 2019-11-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0003_auto_20191119_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='company',
        ),
    ]
