# Generated by Django 2.2.7 on 2020-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0004_auto_20200113_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressLine1',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressLine2',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupName',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='invitationdetails',
            name='emailID',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bankaddress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bankname',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='ifscCode',
            field=models.TextField(max_length=30),
        ),
    ]
