# Generated by Django 2.2.7 on 2019-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0004_remove_userdetails_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='phoneenumber',
            new_name='phonenumber',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dateofbirth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
