# Generated by Django 2.2.7 on 2020-01-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0005_auto_20200113_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryID', models.TextField(max_length=10)),
                ('countryName', models.TextField(max_length=30)),
            ],
        ),
    ]
