# Generated by Django 2.2.7 on 2019-11-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0005_auto_20191130_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
