# Generated by Django 2.2.7 on 2019-11-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0006_auto_20191130_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdescription',
            name='groupID',
        ),
    ]
