# Generated by Django 2.2.7 on 2020-01-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0007_auto_20200114_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
