# Generated by Django 2.2.7 on 2019-12-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0007_remove_groupdescription_groupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdescription',
            name='endDate',
        ),
        migrations.AddField(
            model_name='groupdescription',
            name='noofperiod',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='paymentsFrequency',
            field=models.CharField(max_length=10),
        ),
    ]
