# Generated by Django 2.2.7 on 2020-01-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0008_delete_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countryID', models.TextField(max_length=30)),
                ('countryname', models.TextField(max_length=30)),
            ],
        ),
    ]
