# Generated by Django 2.2.7 on 2020-01-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0010_delete_groupdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('payStatus', models.IntegerField()),
                ('payoutOrder', models.IntegerField()),
                ('groupdescpID', models.IntegerField()),
                ('Username', models.TextField()),
                ('Createby', models.IntegerField()),
                ('isActive', models.IntegerField()),
            ],
        ),
    ]
