# Generated by Django 2.2.7 on 2020-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0011_groupdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paytype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paytypename', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimumgroup', models.IntegerField()),
                ('maximumgroup', models.IntegerField()),
            ],
        ),
    ]
