# Generated by Django 2.2.7 on 2020-01-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0012_paytype_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paytype',
            new_name='Periodtype',
        ),
        migrations.RenameField(
            model_name='periodtype',
            old_name='paytypename',
            new_name='periodtypename',
        ),
    ]
