# Generated by Django 2.2.7 on 2020-01-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0013_auto_20200126_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
