# Generated by Django 2.2.7 on 2020-01-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0014_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimumgroup', models.IntegerField(default=3)),
                ('maximumgroup', models.IntegerField(default=3)),
            ],
        ),
    ]
