# Generated by Django 2.2.7 on 2020-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0015_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('states_id', models.AutoField(primary_key=True, serialize=False)),
                ('states_code', models.TextField(max_length=30)),
                ('states_name', models.TextField(max_length=30)),
            ],
        ),
    ]
